### ISSUE TITLE
Tilføj metadata

### ISSUE THREAD

**Issue by frmi** [dhil/mandriljulekalender#12]
Tilføj metadata så vi kan få en ordenlig beskrivelse på google:
![image](https://github.com/dhil/mandriljulekalender/assets/2438096/5704a5e6-f34c-4c50-923c-20a4ad9d5199)

**Comment by frmi** [comment]
#11 også relateret til denne

**Comment by dhil** [comment]
@heidipi ved du noget om SEO? :')

**Comment by heidipi** [comment]
Jeg har tilføjet en meta description. Feel free to change it

**Comment by frmi** [comment]
Det er perfekt
