### ISSUE TITLE
Sikker jul for alle

### ISSUE THREAD

**Issue by dhil** [dhil/mandriljulekalender#31]
Julen er barmhjertighedens og hyggens tid, men for nogen kan også være en usikker tid. Med Mandriljulekalenderen skulle alle gerne kunne føle sig trygge. Men desværre, så har vores mest loyale bruger gjort mig opmærksom på at vores side ikke automatisk omdirigerer til at benytte HTTPS-protokollen. Jeg ved ikke om det er teknisk muligt at bede Github om at foretage omdirigeringen. Ellers kan vi måske få klienten til at [omdirigere sig selv](https://gist.github.com/konklone/9968713).

**Comment by frmi** [comment]
@dhil https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site
