### ISSUE TITLE
Add cookie confirmation banner

### ISSUE THREAD

**Issue by frmi** [dhil/mandriljulekalender#32]
Vi bruger google analytics, hvilket gør brug af cookies. Vi bør nok implementere et cookie confirmation banner

@dhil

**Comment by dhil** [comment]
Hvad med at vi fjerner Google Analytics?

**Comment by frmi** [comment]
Så ville du ikke vide om der var 3 eller 5 der havde brugt den. Valid point
😅
Med Venlig Hilsen / Best Regards
Frederik Mikkelsen

tors. 26. sep. 2024 12.27 skrev Daniel Hillerström ***@***.***

**Comment by dhil** [comment]
Det er jo med til at sløve indlæsningstiden ned! Hehe.

**Comment by dhil** [comment]
Men vi bruger en funktionel cookie til at gemme julekalenderens tilstand. Så vi skal vel egentlig have et banner eller andet, der siger "vi bruger cookies".
